development:
  adapter: postgresql
  database: artemys
  host: localhost

test:
  adapter: postgresql
  database: artemys
  host: localhost

production:
  adapter: postgresql
  database: artemys
  host: localhost